name: Sync Staging

on:
  push:
    branches: [main]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Set GITHUB_TOKEN
        if: env.GITHUB_TOKEN == ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo "GITHUB_TOKEN=${GITHUB_TOKEN}" >> $GITHUB_ENV

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
          token: ${{ env.GITHUB_TOKEN }}

      - name: push to next branch
        run: |
          git config --local user.name gh-actions
          git config --local user.email gh-actions@github.com

          git push origin main:next
